#################################
# RyuBar User Configuration
#################################

[appearance]

theme=hacker-modern


[applications]

terminal=konsole
browser=firefox
file_manager=dolphin


[paths]

htb=$HOME/HTB


[fonts]

main=Hack Nerd Font
mono=JetBrainsMono Nerd Font
icons=Symbols Nerd Font


[vpn]

type=auto
