#################################
# RyuBar Bars
#################################

[bar/ryubar]

; ===========================
; Geometry
; ===========================

width = 100%
height = ${appearance.height}

offset-x = 0
offset-y = 0

bottom = false

fixed-center = true

radius = ${appearance.radius}

; ===========================
; Appearance
; ===========================

background = ${color.background}
foreground = ${color.foreground}

line-size = 2
border-size = 0

padding-left = 1
padding-right = 1

module-margin = 1

; ===========================
; Fonts
; ===========================

font-0 = ${fonts.font-0}
font-1 = ${fonts.font-1}
font-2 = ${fonts.font-2}

; ===========================
; Modules
; ===========================

modules-left = home separator browser separator terminal

modules-center =iptarget separator workspaces separator vpn

modules-right = cpu separator ram separator battery separator wifi separator bluetooth separator volume separator date separator power

; ===========================
; Interaction
; ===========================

cursor-click = pointer
cursor-scroll = ns-resize

; ===========================
; Window Manager
; ===========================

enable-ipc = true
wm-restack = ewmh

; ===========================
; Monitor
; ===========================

monitor = ${env:MONITOR:}
