#################################
# RyuBar Main Configuration
#################################

include-file = settings.ini
include-file = colors.ini
include-file = fonts.ini
include-file = bars.ini
include-file = modules.ini
