#################################
# RyuBar Modules
#################################


; ===========================
; Separator
; ===========================

[module/separator]

type = custom/text

label = |

label-foreground = ${color.gray}

label-padding = 0

; ===========================
; Battery
; ===========================

[module/battery]
type = custom/script

exec = ~/.config/ryubar/scripts/modules/battery.sh
interval = 10

format = <label>
	label = %output%
	
	click-left = systemsettings kcm_powerdevilprofilesconfig
	
; ===========================
; RyuBar Logo
; ===========================

[module/ryubar-logo]

type = custom/text

label = 

label-foreground = ${color.accent}

click-left = ~/.config/ryubar/scripts/launchers/launcher.sh left
click-right = ~/.config/ryubar/scripts/launchers/launcher.sh right


; ===========================
; Home
; ===========================

[module/home]

type = custom/text

label = 

label-foreground = ${color.foreground}

click-left = ~/.config/ryubar/scripts/launchers/dolphin.sh left
click-right = ~/.config/ryubar/scripts/launchers/dolphin.sh right


; ===========================
; Browser
; ===========================

[module/browser]

type = custom/text

label = 󰖟

label-foreground = ${color.foreground}

click-left = ~/.config/ryubar/scripts/launchers/firefox.sh left
click-right = ~/.config/ryubar/scripts/launchers/firefox.sh right


; ===========================
; Terminal
; ===========================

[module/terminal]

type = custom/text

label = 

label-foreground = ${color.foreground}

click-left = ~/.config/ryubar/scripts/launchers/konsole.sh left
click-right = ~/.config/ryubar/scripts/launchers/konsole.sh right

; ===========================
; Iptarget
; ===========================

[module/iptarget]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/iptarget.sh

interval = 2

format = <label>
label = %output%

; ===========================
; Workspaces
; ===========================

[module/workspaces]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/workspace.sh

interval = 1

format = <label>

label = %output%

scroll-up = ~/.config/ryubar/scripts/modules/workspace-action.sh next
scroll-down = ~/.config/ryubar/scripts/modules/workspace-action.sh previous


; ===========================
; VPN
; ===========================

[module/vpn]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/vpn.sh

interval = 5

format = <label>

label = %output%



; ===========================
; CPU
; ===========================

[module/cpu]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/cpu.sh

interval = 2

format = <label>

label = %output%


; ===========================
; RAM
; ===========================

[module/ram]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/ram.sh

interval = 3

format = <label>

label = %output%


; ===========================
; Wi-Fi
; ===========================

[module/wifi]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/wifi.sh

interval = 5

format = <label>

label = %output%

click-left = plasmawindowed org.kde.plasma.networkmanagement

; ===========================
; Bluetooth
; ===========================

[module/bluetooth]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/bluetooth.sh

interval = 5

format = <label>

label = %output%

click-left = plasmawindowed org.kde.plasma.bluetooth

; ===========================
; Volume
; ===========================

[module/volume]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/volume.sh

interval = 1

format = <label>

label = %output%

click-left = pactl set-sink-mute @DEFAULT_SINK@ toggle
click-right = systemsettings kcm_pulseaudio

; ===========================
; Date
; ===========================

[module/date]

type = custom/script

exec = ~/.config/ryubar/scripts/modules/date.sh

interval = 30

format = <label>

label = %output%


; ===========================
; Power
; ===========================

[module/power]

type = custom/text

label = 

label-foreground = ${color.accent}

click-left = ~/.config/ryubar/scripts/modules/powermenu.sh
