#################################
# RyuBar Laboratory Mode
#################################

background=#101820

foreground=#F8F8F2

accent=#50FA7B

success=#50FA7B

warning=#FFD166

danger=#FF5555

gray=#6272A4


radius=12

height=36

